spring.application.name=TrustDesk

# ===============================
# MySQL Database
# ===============================
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# ===============================
# JPA / Hibernate
# ===============================
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.jdbc.time_zone=UTC
spring.jpa.open-in-view=false

# ===============================
# FlyWay
# ===============================
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration


spring.security.user.name=${APP_SECURITY_USER_NAME}
spring.security.user.password=${APP_SECURITY_USER_PASSWORD}

# ===============================
# Local logs file for @Slf4j
# ===============================
logging.file.name=logs/trustdesk.log
